#!/bin/bash


function scan_finished {
  echo -e "\nScan finished\n"
  echo -e "=========================================================================="
}
function script_help {
  echo  -e "\ntask 6.3 created by Oleh Mykhasiv\n"
  echo -e "MANUAL:\n"
  echo "Script can process one ore more arguments from this list:"
  echo -e "\t--all to displayIP addresses and symbolic names of all hosts in the current subnet"
  echo -e "\t--target [IP] to display a list of open system TCP ports at provided IP"
  echo -e "\t--help to show a manual\n"
}



function script_all {

ip_full=$(ip -f inet addr show enp0s3 | awk '/inet /{ print $2}')
ip_short=$(echo $ip_full | cut -d '.' -f1,2,3)

echo -ne "\nYour IP: " && echo $ip_full
echo -n "Subnet start address: " && echo -e  "\t $ip_short.1"
echo -n "Subnet end address: " && echo -e "\t $ip_short.254\n"
echo "Scan results: "
  for i in {1..254}
    do
      output_ip="$ip_short.$i found! Host info:"

      ping $ip_short.$i -c 1 -w 5 > /dev/null && echo -e "\n$output_ip" && host $ip_short.$i &
      sleep 0.05
   done
scan_finished
}



function script_target {
echo -e "\nScanning open ports:\n"
  if [ ${1:0:2} = "--" ]
    then
      echo "YOU MADE A MISTAKE!"
      script_help
    else
      nc -zv $1 1-65535 2>&1 | grep succeeded
      scan_finished
  fi
}


# =====MAIN PROGRAM=====
if [ $# = 0 ]
then
echo "Please, enter one or more arguments!"
script_help
exit 1
fi

while [ -n "$1" ]
  do
    case "$1" in
      "--help")
        script_help
        ;;


      "--all")
        script_all
        ;;


      "--target")
        shift
        if [ -n "$1" ]
          then
            script_target $1

          else
            read -p "Enter an IP: " ip
            script_target $ip
        fi
        ;;


      *)
        echo "I don't know this parameter: $1"
        script_help
        ;;
    esac
    shift
done
